spring:
  application:
    name: my-finance-tracker
  datasource:
    url: jdbc:postgresql://localhost:5434/myfinancetracker
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect